config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :albums
  root "home#index"


  delete "images/:id/purge", to: "albums#purge", as: "purge_image"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, :name, :description, presence: true
  validates :title, :name, :description, :length => { :minimum => 3 }
  validates :cover_image, :presence => true
  validates :all_tags, :presence => true

  has_one_attached :cover_image
  has_many_attached :images, :dependent => :destroy

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  scope :published, -> { where(publish: true) }
  scope :unpublished, -> { where(publish: false) }

  belongs_to :user

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings , dependent: :destroy
    has_many :albums , through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
     @q = current_user.albums.ransack(params[:q])
     @published = @q.result.published.includes(:tags)
     @unpublished = @q.result.unpublished.includes(:tags)
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album =current_user.albums.new(album_params)
    # @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to root_path, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def purge
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_to  albums_url, notice: "Image deleted"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:name, :description, :title,:all_tags, :cover_image, :publish , images: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @albums =x Album.where(publish: true)
    @q = Album.published.ransack(params[:q])
    @albums = @q.result.includes(:tags)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_footer.html.erb
<body class="d-flex flex-column ">
  <div id="page-content">
    <div class="container text-center">
      <div class="row justify-content-center">
      </div>
    </div>
  </div>
  <footer id="sticky-footer" class="flex-shrink-0 pt-3 bg-dark text-white-50">
    <div class="container text-center fs-5">
      <small>© 2022 Copyright: <a class="text-white" href="#">GALLERY</a></small>
    </div>
    <section class="mb-4 text-center mt-5">
        <!-- Facebook -->
        <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>
        <!-- Twitter -->
        <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee;"
        href="#!"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>
        <!-- Google -->
        <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #dd4b39;"
        href="#!"
        role="button"
        ><i class="fab fa-google"></i
      ></a>
        <!-- Instagram -->
        <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>
        <!-- Linkedin -->
        <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
        <!-- Github -->
        <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
      </section>
  </footer>
</body>

app/views/albums/_form.html.erb
<div class="container bg-light p-5 shadow-lg p-3 mb-5 bg-body rounded" >
  <%= form_with(model: album) do |form| %>
    <div class="form-group">
      <%= form.label :title,class:'form-label fw-bold' %>
      <%= form.text_field :title,  class: "form-control", placeholder: "Title" %>
      <% album.errors.full_messages_for(:title).each do |message| %>
        <p class = "text-danger error"><%= message %></p>
      <% end %>
    </div>
    <div  class=" form-group">
      <%= form.label :name, class:'form-label fw-bold' %>
      <%= form.text_field :name, class: "form-control", placeholder: "Name" %>
      <% album.errors.full_messages_for(:name).each do |message| %>
        <p class = "text-danger"><%= message %></p>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.label :description, class:'form-label fw-bold' %>
      <%= form.text_field :description , class: "form-control", placeholder: "Description"%>
      <% album.errors.full_messages_for(:description).each do |message| %>
        <p class = "text-danger"><%= message %></p>
      <% end %>
    </div>
    <div class="field">
      <%= form.label :Tags, class:'form-label fw-bold text-dark' %>
      <%= form.text_field :all_tags, class: "form-control" , placeholder:"Tags" %>
      <% album.errors.full_messages_for(:all_tags).each do |message| %>
        <p class = "text-danger"><%= message %></p>
      <% end %>
    </div>
    <br>
    <div class="form-group">
      <%= form.label :cover_photo , class:'form-label fw-bold'%>
      <%= form.file_field :cover_image, class:'form-control w-auto' %>
      <% album.errors.full_messages_for(:cover_image).each do |message| %>
        <p class = "text-danger"><%= message %></p>
      <% end %>
    </div>
    <div  class="form-group">
      <%= form.label :image ,class:'form-label fw-bold'%>
      <%= form.file_field :images , multiple: true,  class:'form-control w-auto' %>
    </div>
    <br>
    <div  class="form-group">
      <%= form.label :Publish %>
      <%= form.check_box :publish %>
    </div>
    <br>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/albums/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark sticky-top">
  <div class="container">
    <a class="navbar-brand text-light" href="/">
      <i class="bi bi-camera-fill"></i>
      Gallery
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to  root_path, class: "nav-link text-light " do %>
          Home
        <% end %>
        <% if user_signed_in? %>
          <%= link_to new_album_path, class: "nav-link text-light " do %>
            New Album
          <% end %>
          <%= link_to albums_path, class: "nav-link text-light" do%>
            My Album
          <%end%>
        <%end%>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="fa fa-user"></div>
              <b><%= current_user.email %></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item " do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
              <% end %>
              <%= button_to destroy_user_session_path,method: :delete, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link btn btn-warning me-2" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn btn-primary" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/albums/edit.html.erb
<h1 class ="text-center mt-3 fst-italic text-primary ">Editing album</h1><hr>
<%= render "form", album: @album %>
<br>
<div class ="container">
  <%= link_to "Show this album", @album , class: "btn btn-primary" %> |
  <%= link_to "Back to albums", albums_path , class: "btn btn-warning"%>
</div>

app/views/albums/index.html.erb
<div class ="content ">
  <div class="container">
    <h1 class="text-center mt-5 "> Published Album </h1>
    <hr>
    <div class="search mt-4 d-flex justify-content-end">
      <%= search_form_for @q do |f|%>
        <%= f.search_field :tags_name_or_name_cont , placeholder: "Search By Tag", class:"rounded" %>
        <%= f.submit "Search", class:"rounded"%>
      <% end %>
    </div>
    <div class= "row mt-5">
      <% @published.each do |album| %>
        <div class = "col-lg-4 text-center shadow-lg p-3 mb-5 bg-body rounded">
          <div class="card m-3 ">
            <h3 class="card-title text-dark">
              <strong>Album:</strong>
              <%= album.title %>
            </h3>
            <%if album.cover_image.attached? %>
              <div class="card-header">
                <%=link_to album_path(id: album.id) do %>
                  <%= image_tag album.cover_image ,  class: 'img-fluid' %>
                <%end%>
              </div>
            <%end%>
            <div class="card-body">
              <h5 class="card-title">
                <center> <strong>Name: </strong><%= album.name %><br>
                </center>
                <center><strong>Description: </strong><%= album.description %></center>
                <hr>
                <strong>Created at: </strong>
                <span class="text-muted"><%= album.created_at.to_date%></span>
                <br>
                <br>
                <strong>Total Images: </strong>
                <span class="text-muted"><%= album.images.count%></span>
                <br>
                <br>
                <strong>Tag: </strong>
                <span class="text-muted"><%= album.all_tags %></span>
              </div>
              <div class="card-footer text-muted">
                <%= link_to "View" ,album_path(album) , class: "btn btn-info delete fs-5" %>
                <%= link_to "edit album" , edit_album_path(album) , class: "btn btn-primary edit"%>
                <%= button_to 'delete' ,  album_path(album), method: :delete, class: "btn btn-danger fs-5 mt-5" %>
              </div>
            </div>
            <br>
          </div>
        <% end %>
        <h1 class="text-center">Unpublished Album</h1>
        <hr>
        <div class= "row mt-5">
          <% @unpublished.each do |unpublish| %>
            <div class = "col-lg-4 text-center shadow-lg p-3 mb-5 bg-body rounded">
              <div class="card m-3 ">
                <h3 class="card-title">
                  <strong>Album:</strong>
                  <%= unpublish.title %>
                </h3>
                <%if unpublish.cover_image.attached? %>
                  <div class="card-header">
                    <%=link_to album_path(id: unpublish.id) do %>
                      <%= image_tag unpublish.cover_image ,  class: 'img-fluid' %>
                    <%end%>
                  </div>
                <%end%>
                <div class="card-body">
                  <h5 class="card-title">
                    <center> <strong>Name: </strong><%= unpublish.name %><br>
                    </center>
                    <center><strong>Description: </strong><%= unpublish.description %></center>
                    <hr>
                    <strong>Created at: </strong>
                    <span class="text-muted"><%= unpublish.created_at.to_date%></span>
                    <br>
                    <br>
                    <strong>Total Images: </strong>
                    <span class="text-muted"><%= unpublish.images.count%></span>
                    <br>
                    <br>
                    <strong>Tag: </strong>
                    <span class="text-muted"><%= unpublish.all_tags %></span>
                  </div>
                  <div class="card-footer text-muted">
                    <%= link_to "View" ,album_path(unpublish) , class: "btn btn-info delete fs-5" %>
                    <%= link_to "edit album" , edit_album_path(unpublish) , class: "btn btn-primary edit"%>
                    <%= button_to 'delete' ,  album_path(unpublish), method: :delete, class: "btn btn-danger fs-5 mt-5 mb-5" %>
                  </div>
                </div>
                <br>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/albums/new.html.erb
<section class="bg-light">
  <div class="container  ">
    <h1 class="mb-5 text-center text-success pt-5">Create New album</h1>
    <%= render "form", album: @album %>
    <br>
    <div>
      <%= link_to "Back to albums", albums_path, class: "btn btn-primary mb-5" %>
    </div>
  </div>
</section>

app/views/albums/show.html.erb
<div class="container">
  <h4 class="my-5 text-center"><b>Description:</b><%= @album.description  %></h4>
  <hr>
  <button type="button" class="btn btn-secondary fs-5" data-bs-toggle="modal" data-bs-target="#exampleModal">
    <i class="fa fa-upload"></i></button>
  <div class="row mt-5">
    <% @album.images.each do |image| %>
      <div class="col-lg-4 my-2">
        <div class="card ">
          <%= link_to image, target:"_blank" do %>
            <%= image_tag(image, class:"img-fluid img") %>
          <%end%>
          <div class="card-footer ">
            <%= link_to  edit_album_path(@album) , class: "btn btn-dark fs-5 " , style: "float: left;"  do %>
              <i class="fas fa-edit"></i>
            <%end%>
            <%if current_user.albums%>
              <%= button_to purge_image_path(id: image.id), method: :delete,  class:"btn btn-danger fs-5" , style:"float: right;" do %>
                <i class="fas fa-trash"></i>
              <%end%>
            <%end%>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="text-dark text-center">Uplaod Images!</h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: @album do |form| %>
          <div class="field">
            <%= form.file_field :images,  multiple: true, class: "form-control w-50" %>
          </div>
          <br />
          <div>
            <%= form.submit "Add Images", class: "btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class ="content">
  <div class="container">
    <h1 class="text-center my-5"> All Publish Album</h1>
    <hr>
      <div class="search mt-4 d-flex justify-content-end">
      <%= search_form_for @q, url: root_path do |f|%>
        <%= f.search_field :tags_name_or_name_eq , placeholder: "Search By Tag or Name", class:"rounded"%>
        <%= f.submit "Search", class:"rounded" %>
      <% end %>
    </div>
      <div class= "row mt-5">
        <% @albums.each do |album| %>
          <div class = "col-lg-4 text-center shadow-lg p-3 mb-5 bg-body rounded">
            <div class="card m-3 ">
              <h3 class="card-title text-dark">
                <strong>Album:</strong>
                <%= album.title %>
              </h3>
              <%if album.cover_image.attached? %>
                <div class="card-header">
                  <%=link_to album_path(id: album.id) do %>
                    <%= image_tag album.cover_image ,  class: 'img-fluid' %>
                  <%end%>
                </div>
              <%end%>
              <div class="card-body">
                <h5 class="card-title">
                  <center> <strong>Name: </strong><%= album.name %><br>
                  </center>
                  <center><strong>Description: </strong><%= album.description %></center>
                  <hr>
                  <strong>Created at: </strong>
                  <span class="text-muted"><%= album.created_at.to_date%></span>
                  <br>
                  <br>
                  <strong>Total Images: </strong>
                  <span class="text-muted"><%= album.images.count%></span>
                  <br>
                  <br>
                  <strong>Tag: </strong>
                  <span class="text-muted"><%= album.all_tags %></span>
                </div>
              </div>
              <br>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>   
  </head>
  <body>
    <%= render "albums/navbar"%>
    <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </div>
    <%=yield%>
    <%=render "albums/footer"%>
    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>